
#!/usr/bin/env bash
SECONDS="10s"
STATS_SECONDS="10"
DELAY="sleep $SECONDS"

PERFORMANCE_TEST="performance-test-results"
#SPLIT_CC="split-cc"
CC_VMSTAT="cc-vmstat" 
CC_MPSTAT="cc-mpstat" 
CC_PAGEFAULTS="pagefaults" 
CC_SIEGE="cc-siege"
VMSTAT="vmstat -n -w -S M 1 $STATS_SECONDS"
MPSTAT="mpstat -P ALL 1 $STATS_SECONDS"
SAR="sar -B 1 $STATS_SECONDS"
RUN1_TXT="run1.txt"
RUN2_TXT="run2.txt"
RUN3_TXT="run3.txt"
RUN4_TXT="run4.txt"
RUN5_TXT="run5.txt"

CONCURRENCY_RUN2="20"
CONCURRENCY_RUN3="50"
CONCURRENCY_RUN4="50"
CONCURRENCY_RUN5="50"
LAB_URL="http://cse01-iiith.vlabs.ac.in/"
VLABS_URL="http://vlabs.ac.in/"

SIEGE2="siege -c $CONCURRENCY_RUN2 -t $SECONDS"
SIEGE3="siege -c $CONCURRENCY_RUN3 -t $SECONDS"
SIEGE4="siege -c $CONCURRENCY_RUN4 -t $SECONDS"
SIEGE5="siege -c $CONCURRENCY_RUN5 -t $SECONDS"
